"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protocol definition file for GTFS Realtime.

GTFS Realtime lets transit agencies provide consumers with realtime
information about disruptions to their service (stations closed, lines not
operating, important delays etc), location of their vehicles and expected
arrival times.

This protocol is published at:
https://github.com/google/transit/tree/master/gtfs-realtime
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class FeedMessage(_message.Message):
    """The contents of a feed message.
    A feed is a continuous stream of feed messages. Each message in the stream is
    obtained as a response to an appropriate HTTP GET request.
    A realtime feed is always defined with relation to an existing GTFS feed.
    All the entity ids are resolved with respect to the GTFS feed.
    Note that "required" and "optional" as stated in this file refer to Protocol
    Buffer cardinality, not semantic cardinality.  See reference.md at
    https://github.com/google/transit/tree/master/gtfs-realtime for field
    semantic cardinality.
    """

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    ENTITY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def header(self) -> Global___FeedHeader:
        """Metadata about this feed and feed message."""

    @_builtins.property
    def entity(self) -> _containers.RepeatedCompositeFieldContainer[Global___FeedEntity]:
        """Contents of the feed."""

    def __init__(
        self,
        *,
        header: Global___FeedHeader | None = ...,
        entity: _abc.Iterable[Global___FeedEntity] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entity", b"entity", "header", b"header"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FeedMessage: _TypeAlias = FeedMessage  # noqa: Y015

@_typing.final
class FeedHeader(_message.Message):
    """Metadata about a feed, included in feed messages."""

    DESCRIPTOR: _descriptor.Descriptor

    class _Incrementality:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _IncrementalityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[FeedHeader._Incrementality.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        FULL_DATASET: FeedHeader._Incrementality.ValueType  # 0
        DIFFERENTIAL: FeedHeader._Incrementality.ValueType  # 1

    class Incrementality(_Incrementality, metaclass=_IncrementalityEnumTypeWrapper):
        """Determines whether the current fetch is incremental.  Currently,
        DIFFERENTIAL mode is unsupported and behavior is unspecified for feeds
        that use this mode.  There are discussions on the GTFS Realtime mailing
        list around fully specifying the behavior of DIFFERENTIAL mode and the
        documentation will be updated when those discussions are finalized.
        """

    FULL_DATASET: FeedHeader.Incrementality.ValueType  # 0
    DIFFERENTIAL: FeedHeader.Incrementality.ValueType  # 1

    GTFS_REALTIME_VERSION_FIELD_NUMBER: _builtins.int
    INCREMENTALITY_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    gtfs_realtime_version: _builtins.str
    """Version of the feed specification.
    The current version is 2.0.  Valid versions are "2.0", "1.0".
    """
    incrementality: Global___FeedHeader.Incrementality.ValueType
    timestamp: _builtins.int
    """This timestamp identifies the moment when the content of this feed has been
    created (in server time). In POSIX time (i.e., number of seconds since
    January 1st 1970 00:00:00 UTC).
    """
    def __init__(
        self,
        *,
        gtfs_realtime_version: _builtins.str | None = ...,
        incrementality: Global___FeedHeader.Incrementality.ValueType | None = ...,
        timestamp: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["gtfs_realtime_version", b"gtfs_realtime_version", "incrementality", b"incrementality", "timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gtfs_realtime_version", b"gtfs_realtime_version", "incrementality", b"incrementality", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FeedHeader: _TypeAlias = FeedHeader  # noqa: Y015

@_typing.final
class FeedEntity(_message.Message):
    """A definition (or update) of an entity in the transit feed."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    IS_DELETED_FIELD_NUMBER: _builtins.int
    TRIP_UPDATE_FIELD_NUMBER: _builtins.int
    VEHICLE_FIELD_NUMBER: _builtins.int
    ALERT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """The ids are used only to provide incrementality support. The id should be
    unique within a FeedMessage. Consequent FeedMessages may contain
    FeedEntities with the same id. In case of a DIFFERENTIAL update the new
    FeedEntity with some id will replace the old FeedEntity with the same id
    (or delete it - see is_deleted below).
    The actual GTFS entities (e.g. stations, routes, trips) referenced by the
    feed must be specified by explicit selectors (see EntitySelector below for
    more info).
    """
    is_deleted: _builtins.bool
    """Whether this entity is to be deleted. Relevant only for incremental
    fetches.
    """
    @_builtins.property
    def trip_update(self) -> Global___TripUpdate:
        """Data about the entity itself. Exactly one of the following fields must be
        present (unless the entity is being deleted).
        """

    @_builtins.property
    def vehicle(self) -> Global___VehiclePosition: ...
    @_builtins.property
    def alert(self) -> Global___Alert: ...
    def __init__(
        self,
        *,
        id: _builtins.str | None = ...,
        is_deleted: _builtins.bool | None = ...,
        trip_update: Global___TripUpdate | None = ...,
        vehicle: Global___VehiclePosition | None = ...,
        alert: Global___Alert | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["alert", b"alert", "id", b"id", "is_deleted", b"is_deleted", "trip_update", b"trip_update", "vehicle", b"vehicle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alert", b"alert", "id", b"id", "is_deleted", b"is_deleted", "trip_update", b"trip_update", "vehicle", b"vehicle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FeedEntity: _TypeAlias = FeedEntity  # noqa: Y015

@_typing.final
class TripUpdate(_message.Message):
    """
    Entities used in the feed.

    Realtime update of the progress of a vehicle along a trip.
    Depending on the value of ScheduleRelationship, a TripUpdate can specify:
    - A trip that proceeds along the schedule.
    - A trip that proceeds along a route but has no fixed schedule.
    - A trip that have been added or removed with regard to schedule.

    The updates can be for future, predicted arrival/departure events, or for
    past events that already occurred.
    Normally, updates should get more precise and more certain (see
    uncertainty below) as the events gets closer to current time.
    Even if that is not possible, the information for past events should be
    precise and certain. In particular, if an update points to time in the past
    but its update's uncertainty is not 0, the client should conclude that the
    update is a (wrong) prediction and that the trip has not completed yet.

    Note that the update can describe a trip that is already completed.
    To this end, it is enough to provide an update for the last stop of the trip.
    If the time of that is in the past, the client will conclude from that that
    the whole trip is in the past (it is possible, although inconsequential, to
    also provide updates for preceding stops).
    This option is most relevant for a trip that has completed ahead of schedule,
    but according to the schedule, the trip is still proceeding at the current
    time. Removing the updates for this trip could make the client assume
    that the trip is still proceeding.
    Note that the feed provider is allowed, but not required, to purge past
    updates - this is one case where this would be practically useful.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class StopTimeEvent(_message.Message):
        """Timing information for a single predicted event (either arrival or
        departure).
        Timing consists of delay and/or estimated time, and uncertainty.
        - delay should be used when the prediction is given relative to some
          existing schedule in GTFS.
        - time should be given whether there is a predicted schedule or not. If
          both time and delay are specified, time will take precedence
          (although normally, time, if given for a scheduled trip, should be
          equal to scheduled time in GTFS + delay).

        Uncertainty applies equally to both time and delay.
        The uncertainty roughly specifies the expected error in true delay (but
        note, we don't yet define its precise statistical meaning). It's possible
        for the uncertainty to be 0, for example for trains that are driven under
        computer timing control.
        """

        DESCRIPTOR: _descriptor.Descriptor

        DELAY_FIELD_NUMBER: _builtins.int
        TIME_FIELD_NUMBER: _builtins.int
        UNCERTAINTY_FIELD_NUMBER: _builtins.int
        delay: _builtins.int
        """Delay (in seconds) can be positive (meaning that the vehicle is late) or
        negative (meaning that the vehicle is ahead of schedule). Delay of 0
        means that the vehicle is exactly on time.
        """
        time: _builtins.int
        """Event as absolute time.
        In Unix time (i.e., number of seconds since January 1st 1970 00:00:00
        UTC).
        """
        uncertainty: _builtins.int
        """If uncertainty is omitted, it is interpreted as unknown.
        If the prediction is unknown or too uncertain, the delay (or time) field
        should be empty. In such case, the uncertainty field is ignored.
        To specify a completely certain prediction, set its uncertainty to 0.
        """
        def __init__(
            self,
            *,
            delay: _builtins.int | None = ...,
            time: _builtins.int | None = ...,
            uncertainty: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["delay", b"delay", "time", b"time", "uncertainty", b"uncertainty"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["delay", b"delay", "time", b"time", "uncertainty", b"uncertainty"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class StopTimeUpdate(_message.Message):
        """Realtime update for arrival and/or departure events for a given stop on a
        trip. Updates can be supplied for both past and future events.
        The producer is allowed, although not required, to drop past events.
        The update is linked to a specific stop either through stop_sequence or
        stop_id, so one of the fields below must necessarily be set.
        See the documentation in TripDescriptor for more information.
        """

        DESCRIPTOR: _descriptor.Descriptor

        class _ScheduleRelationship:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _ScheduleRelationshipEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TripUpdate.StopTimeUpdate._ScheduleRelationship.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            SCHEDULED: TripUpdate.StopTimeUpdate._ScheduleRelationship.ValueType  # 0
            """The vehicle is proceeding in accordance with its static schedule of
            stops, although not necessarily according to the times of the schedule.
            At least one of arrival and departure must be provided. If the schedule
            for this stop contains both arrival and departure times then so must
            this update. Frequency-based trips (GTFS frequencies.txt with exact_times = 0)
            should not have a SCHEDULED value and should use UNSCHEDULED instead.
            """
            SKIPPED: TripUpdate.StopTimeUpdate._ScheduleRelationship.ValueType  # 1
            """The stop is skipped, i.e., the vehicle will not stop at this stop.
            Arrival and departure are optional.
            """
            NO_DATA: TripUpdate.StopTimeUpdate._ScheduleRelationship.ValueType  # 2
            """No data is given for this stop. The main intention for this value is to
            give the predictions only for part of a trip, i.e., if the last update
            for a trip has a NO_DATA specifier, then StopTimes for the rest of the
            stops in the trip are considered to be unspecified as well.
            Neither arrival nor departure should be supplied.
            """
            UNSCHEDULED: TripUpdate.StopTimeUpdate._ScheduleRelationship.ValueType  # 3
            """The vehicle is operating a trip defined in GTFS frequencies.txt with exact_times = 0.
            This value should not be used for trips that are not defined in GTFS frequencies.txt,
            or trips in GTFS frequencies.txt with exact_times = 1. Trips containing StopTimeUpdates
            with ScheduleRelationship=UNSCHEDULED must also set TripDescriptor.ScheduleRelationship=UNSCHEDULED.
            NOTE: This field is still experimental, and subject to change. It may be
            formally adopted in the future.
            """

        class ScheduleRelationship(_ScheduleRelationship, metaclass=_ScheduleRelationshipEnumTypeWrapper):
            """The relation between this StopTime and the static schedule."""

        SCHEDULED: TripUpdate.StopTimeUpdate.ScheduleRelationship.ValueType  # 0
        """The vehicle is proceeding in accordance with its static schedule of
        stops, although not necessarily according to the times of the schedule.
        At least one of arrival and departure must be provided. If the schedule
        for this stop contains both arrival and departure times then so must
        this update. Frequency-based trips (GTFS frequencies.txt with exact_times = 0)
        should not have a SCHEDULED value and should use UNSCHEDULED instead.
        """
        SKIPPED: TripUpdate.StopTimeUpdate.ScheduleRelationship.ValueType  # 1
        """The stop is skipped, i.e., the vehicle will not stop at this stop.
        Arrival and departure are optional.
        """
        NO_DATA: TripUpdate.StopTimeUpdate.ScheduleRelationship.ValueType  # 2
        """No data is given for this stop. The main intention for this value is to
        give the predictions only for part of a trip, i.e., if the last update
        for a trip has a NO_DATA specifier, then StopTimes for the rest of the
        stops in the trip are considered to be unspecified as well.
        Neither arrival nor departure should be supplied.
        """
        UNSCHEDULED: TripUpdate.StopTimeUpdate.ScheduleRelationship.ValueType  # 3
        """The vehicle is operating a trip defined in GTFS frequencies.txt with exact_times = 0.
        This value should not be used for trips that are not defined in GTFS frequencies.txt,
        or trips in GTFS frequencies.txt with exact_times = 1. Trips containing StopTimeUpdates
        with ScheduleRelationship=UNSCHEDULED must also set TripDescriptor.ScheduleRelationship=UNSCHEDULED.
        NOTE: This field is still experimental, and subject to change. It may be
        formally adopted in the future.
        """

        @_typing.final
        class StopTimeProperties(_message.Message):
            """Provides the updated values for the stop time.
            NOTE: This message is still experimental, and subject to change. It may be formally adopted in the future.
            """

            DESCRIPTOR: _descriptor.Descriptor

            ASSIGNED_STOP_ID_FIELD_NUMBER: _builtins.int
            assigned_stop_id: _builtins.str
            """Supports real-time stop assignments. Refers to a stop_id defined in the GTFS stops.txt.
            The new assigned_stop_id should not result in a significantly different trip experience for the end user than
            the stop_id defined in GTFS stop_times.txt. In other words, the end user should not view this new stop_id as an
            "unusual change" if the new stop was presented within an app without any additional context.
            For example, this field is intended to be used for platform assignments by using a stop_id that belongs to the
            same station as the stop originally defined in GTFS stop_times.txt.
            To assign a stop without providing any real-time arrival or departure predictions, populate this field and set
            StopTimeUpdate.schedule_relationship = NO_DATA.
            If this field is populated, it is preferred to omit `StopTimeUpdate.stop_id` and use only `StopTimeUpdate.stop_sequence`. If
            `StopTimeProperties.assigned_stop_id` and `StopTimeUpdate.stop_id` are populated, `StopTimeUpdate.stop_id` must match `assigned_stop_id`.
            Platform assignments should be reflected in other GTFS-realtime fields as well
            (e.g., `VehiclePosition.stop_id`).
            NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
            """
            def __init__(
                self,
                *,
                assigned_stop_id: _builtins.str | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["assigned_stop_id", b"assigned_stop_id"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["assigned_stop_id", b"assigned_stop_id"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        STOP_SEQUENCE_FIELD_NUMBER: _builtins.int
        STOP_ID_FIELD_NUMBER: _builtins.int
        ARRIVAL_FIELD_NUMBER: _builtins.int
        DEPARTURE_FIELD_NUMBER: _builtins.int
        SCHEDULE_RELATIONSHIP_FIELD_NUMBER: _builtins.int
        STOP_TIME_PROPERTIES_FIELD_NUMBER: _builtins.int
        stop_sequence: _builtins.int
        """Must be the same as in stop_times.txt in the corresponding GTFS feed."""
        stop_id: _builtins.str
        """Must be the same as in stops.txt in the corresponding GTFS feed."""
        schedule_relationship: Global___TripUpdate.StopTimeUpdate.ScheduleRelationship.ValueType
        @_builtins.property
        def arrival(self) -> Global___TripUpdate.StopTimeEvent: ...
        @_builtins.property
        def departure(self) -> Global___TripUpdate.StopTimeEvent: ...
        @_builtins.property
        def stop_time_properties(self) -> Global___TripUpdate.StopTimeUpdate.StopTimeProperties:
            """Realtime updates for certain properties defined within GTFS stop_times.txt
            NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
            """

        def __init__(
            self,
            *,
            stop_sequence: _builtins.int | None = ...,
            stop_id: _builtins.str | None = ...,
            arrival: Global___TripUpdate.StopTimeEvent | None = ...,
            departure: Global___TripUpdate.StopTimeEvent | None = ...,
            schedule_relationship: Global___TripUpdate.StopTimeUpdate.ScheduleRelationship.ValueType | None = ...,
            stop_time_properties: Global___TripUpdate.StopTimeUpdate.StopTimeProperties | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["arrival", b"arrival", "departure", b"departure", "schedule_relationship", b"schedule_relationship", "stop_id", b"stop_id", "stop_sequence", b"stop_sequence", "stop_time_properties", b"stop_time_properties"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["arrival", b"arrival", "departure", b"departure", "schedule_relationship", b"schedule_relationship", "stop_id", b"stop_id", "stop_sequence", b"stop_sequence", "stop_time_properties", b"stop_time_properties"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class TripProperties(_message.Message):
        """Defines updated properties of the trip
        NOTE: This message is still experimental, and subject to change. It may be formally adopted in the future.
        """

        DESCRIPTOR: _descriptor.Descriptor

        TRIP_ID_FIELD_NUMBER: _builtins.int
        START_DATE_FIELD_NUMBER: _builtins.int
        START_TIME_FIELD_NUMBER: _builtins.int
        trip_id: _builtins.str
        start_date: _builtins.str
        start_time: _builtins.str
        def __init__(
            self,
            *,
            trip_id: _builtins.str | None = ...,
            start_date: _builtins.str | None = ...,
            start_time: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["start_date", b"start_date", "start_time", b"start_time", "trip_id", b"trip_id"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["start_date", b"start_date", "start_time", b"start_time", "trip_id", b"trip_id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TRIP_FIELD_NUMBER: _builtins.int
    VEHICLE_FIELD_NUMBER: _builtins.int
    STOP_TIME_UPDATE_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    DELAY_FIELD_NUMBER: _builtins.int
    TRIP_PROPERTIES_FIELD_NUMBER: _builtins.int
    timestamp: _builtins.int
    """Moment at which the vehicle's real-time progress was measured. In POSIX
    time (i.e., the number of seconds since January 1st 1970 00:00:00 UTC).
    """
    delay: _builtins.int
    """The current schedule deviation for the trip."""
    @_builtins.property
    def trip(self) -> Global___TripDescriptor:
        """The Trip that this message applies to. There can be at most one
        TripUpdate entity for each actual trip instance.
        If there is none, that means there is no prediction information available.
        It does *not* mean that the trip is progressing according to schedule.
        """

    @_builtins.property
    def vehicle(self) -> Global___VehicleDescriptor:
        """Additional information on the vehicle that is serving this trip."""

    @_builtins.property
    def stop_time_update(self) -> _containers.RepeatedCompositeFieldContainer[Global___TripUpdate.StopTimeUpdate]:
        """Updates to StopTimes for the trip (both future, i.e., predictions, and in
        some cases, past ones, i.e., those that already happened).
        The updates must be sorted by stop_sequence, and apply for all the
        following stops of the trip up to the next specified one.
        """

    @_builtins.property
    def trip_properties(self) -> Global___TripUpdate.TripProperties: ...
    def __init__(
        self,
        *,
        trip: Global___TripDescriptor | None = ...,
        vehicle: Global___VehicleDescriptor | None = ...,
        stop_time_update: _abc.Iterable[Global___TripUpdate.StopTimeUpdate] | None = ...,
        timestamp: _builtins.int | None = ...,
        delay: _builtins.int | None = ...,
        trip_properties: Global___TripUpdate.TripProperties | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["delay", b"delay", "timestamp", b"timestamp", "trip", b"trip", "trip_properties", b"trip_properties", "vehicle", b"vehicle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delay", b"delay", "stop_time_update", b"stop_time_update", "timestamp", b"timestamp", "trip", b"trip", "trip_properties", b"trip_properties", "vehicle", b"vehicle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TripUpdate: _TypeAlias = TripUpdate  # noqa: Y015

@_typing.final
class VehiclePosition(_message.Message):
    """Realtime positioning information for a given vehicle."""

    DESCRIPTOR: _descriptor.Descriptor

    class _VehicleStopStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _VehicleStopStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[VehiclePosition._VehicleStopStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        INCOMING_AT: VehiclePosition._VehicleStopStatus.ValueType  # 0
        STOPPED_AT: VehiclePosition._VehicleStopStatus.ValueType  # 1
        IN_TRANSIT_TO: VehiclePosition._VehicleStopStatus.ValueType  # 2

    class VehicleStopStatus(_VehicleStopStatus, metaclass=_VehicleStopStatusEnumTypeWrapper): ...
    INCOMING_AT: VehiclePosition.VehicleStopStatus.ValueType  # 0
    STOPPED_AT: VehiclePosition.VehicleStopStatus.ValueType  # 1
    IN_TRANSIT_TO: VehiclePosition.VehicleStopStatus.ValueType  # 2

    class _CongestionLevel:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _CongestionLevelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[VehiclePosition._CongestionLevel.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN_CONGESTION_LEVEL: VehiclePosition._CongestionLevel.ValueType  # 0
        RUNNING_SMOOTHLY: VehiclePosition._CongestionLevel.ValueType  # 1
        STOP_AND_GO: VehiclePosition._CongestionLevel.ValueType  # 2
        CONGESTION: VehiclePosition._CongestionLevel.ValueType  # 3
        SEVERE_CONGESTION: VehiclePosition._CongestionLevel.ValueType  # 4

    class CongestionLevel(_CongestionLevel, metaclass=_CongestionLevelEnumTypeWrapper): ...
    UNKNOWN_CONGESTION_LEVEL: VehiclePosition.CongestionLevel.ValueType  # 0
    RUNNING_SMOOTHLY: VehiclePosition.CongestionLevel.ValueType  # 1
    STOP_AND_GO: VehiclePosition.CongestionLevel.ValueType  # 2
    CONGESTION: VehiclePosition.CongestionLevel.ValueType  # 3
    SEVERE_CONGESTION: VehiclePosition.CongestionLevel.ValueType  # 4

    class _OccupancyStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _OccupancyStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[VehiclePosition._OccupancyStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        EMPTY: VehiclePosition._OccupancyStatus.ValueType  # 0
        MANY_SEATS_AVAILABLE: VehiclePosition._OccupancyStatus.ValueType  # 1
        FEW_SEATS_AVAILABLE: VehiclePosition._OccupancyStatus.ValueType  # 2
        STANDING_ROOM_ONLY: VehiclePosition._OccupancyStatus.ValueType  # 3
        CRUSHED_STANDING_ROOM_ONLY: VehiclePosition._OccupancyStatus.ValueType  # 4
        FULL: VehiclePosition._OccupancyStatus.ValueType  # 5
        NOT_ACCEPTING_PASSENGERS: VehiclePosition._OccupancyStatus.ValueType  # 6
        NO_DATA_AVAILABLE: VehiclePosition._OccupancyStatus.ValueType  # 7
        NOT_BOARDABLE: VehiclePosition._OccupancyStatus.ValueType  # 8

    class OccupancyStatus(_OccupancyStatus, metaclass=_OccupancyStatusEnumTypeWrapper): ...
    EMPTY: VehiclePosition.OccupancyStatus.ValueType  # 0
    MANY_SEATS_AVAILABLE: VehiclePosition.OccupancyStatus.ValueType  # 1
    FEW_SEATS_AVAILABLE: VehiclePosition.OccupancyStatus.ValueType  # 2
    STANDING_ROOM_ONLY: VehiclePosition.OccupancyStatus.ValueType  # 3
    CRUSHED_STANDING_ROOM_ONLY: VehiclePosition.OccupancyStatus.ValueType  # 4
    FULL: VehiclePosition.OccupancyStatus.ValueType  # 5
    NOT_ACCEPTING_PASSENGERS: VehiclePosition.OccupancyStatus.ValueType  # 6
    NO_DATA_AVAILABLE: VehiclePosition.OccupancyStatus.ValueType  # 7
    NOT_BOARDABLE: VehiclePosition.OccupancyStatus.ValueType  # 8

    @_typing.final
    class CarriageDetails(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ID_FIELD_NUMBER: _builtins.int
        LABEL_FIELD_NUMBER: _builtins.int
        OCCUPANCY_STATUS_FIELD_NUMBER: _builtins.int
        OCCUPANCY_PERCENTAGE_FIELD_NUMBER: _builtins.int
        CARRIAGE_SEQUENCE_FIELD_NUMBER: _builtins.int
        id: _builtins.str
        label: _builtins.str
        occupancy_status: Global___VehiclePosition.OccupancyStatus.ValueType
        occupancy_percentage: _builtins.int
        carriage_sequence: _builtins.int
        def __init__(
            self,
            *,
            id: _builtins.str | None = ...,
            label: _builtins.str | None = ...,
            occupancy_status: Global___VehiclePosition.OccupancyStatus.ValueType | None = ...,
            occupancy_percentage: _builtins.int | None = ...,
            carriage_sequence: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["carriage_sequence", b"carriage_sequence", "id", b"id", "label", b"label", "occupancy_percentage", b"occupancy_percentage", "occupancy_status", b"occupancy_status"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["carriage_sequence", b"carriage_sequence", "id", b"id", "label", b"label", "occupancy_percentage", b"occupancy_percentage", "occupancy_status", b"occupancy_status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TRIP_FIELD_NUMBER: _builtins.int
    VEHICLE_FIELD_NUMBER: _builtins.int
    POSITION_FIELD_NUMBER: _builtins.int
    CURRENT_STOP_SEQUENCE_FIELD_NUMBER: _builtins.int
    STOP_ID_FIELD_NUMBER: _builtins.int
    CURRENT_STATUS_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    CONGESTION_LEVEL_FIELD_NUMBER: _builtins.int
    OCCUPANCY_STATUS_FIELD_NUMBER: _builtins.int
    OCCUPANCY_PERCENTAGE_FIELD_NUMBER: _builtins.int
    MULTI_CARRIAGE_DETAILS_FIELD_NUMBER: _builtins.int
    current_stop_sequence: _builtins.int
    stop_id: _builtins.str
    current_status: Global___VehiclePosition.VehicleStopStatus.ValueType
    timestamp: _builtins.int
    congestion_level: Global___VehiclePosition.CongestionLevel.ValueType
    occupancy_status: Global___VehiclePosition.OccupancyStatus.ValueType
    occupancy_percentage: _builtins.int
    @_builtins.property
    def trip(self) -> Global___TripDescriptor: ...
    @_builtins.property
    def vehicle(self) -> Global___VehicleDescriptor: ...
    @_builtins.property
    def position(self) -> Global___Position: ...
    @_builtins.property
    def multi_carriage_details(self) -> _containers.RepeatedCompositeFieldContainer[Global___VehiclePosition.CarriageDetails]: ...
    def __init__(
        self,
        *,
        trip: Global___TripDescriptor | None = ...,
        vehicle: Global___VehicleDescriptor | None = ...,
        position: Global___Position | None = ...,
        current_stop_sequence: _builtins.int | None = ...,
        stop_id: _builtins.str | None = ...,
        current_status: Global___VehiclePosition.VehicleStopStatus.ValueType | None = ...,
        timestamp: _builtins.int | None = ...,
        congestion_level: Global___VehiclePosition.CongestionLevel.ValueType | None = ...,
        occupancy_status: Global___VehiclePosition.OccupancyStatus.ValueType | None = ...,
        occupancy_percentage: _builtins.int | None = ...,
        multi_carriage_details: _abc.Iterable[Global___VehiclePosition.CarriageDetails] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["congestion_level", b"congestion_level", "current_status", b"current_status", "current_stop_sequence", b"current_stop_sequence", "occupancy_percentage", b"occupancy_percentage", "occupancy_status", b"occupancy_status", "position", b"position", "stop_id", b"stop_id", "timestamp", b"timestamp", "trip", b"trip", "vehicle", b"vehicle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["congestion_level", b"congestion_level", "current_status", b"current_status", "current_stop_sequence", b"current_stop_sequence", "multi_carriage_details", b"multi_carriage_details", "occupancy_percentage", b"occupancy_percentage", "occupancy_status", b"occupancy_status", "position", b"position", "stop_id", b"stop_id", "timestamp", b"timestamp", "trip", b"trip", "vehicle", b"vehicle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VehiclePosition: _TypeAlias = VehiclePosition  # noqa: Y015

@_typing.final
class Alert(_message.Message):
    """An alert, indicating some sort of incident in the public transit network."""

    DESCRIPTOR: _descriptor.Descriptor

    class _Cause:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _CauseEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Alert._Cause.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN_CAUSE: Alert._Cause.ValueType  # 1
        OTHER_CAUSE: Alert._Cause.ValueType  # 2
        TECHNICAL_PROBLEM: Alert._Cause.ValueType  # 3
        STRIKE: Alert._Cause.ValueType  # 4
        DEMONSTRATION: Alert._Cause.ValueType  # 5
        ACCIDENT: Alert._Cause.ValueType  # 6
        HOLIDAY: Alert._Cause.ValueType  # 7
        WEATHER: Alert._Cause.ValueType  # 8
        MAINTENANCE: Alert._Cause.ValueType  # 9
        CONSTRUCTION: Alert._Cause.ValueType  # 10
        POLICE_ACTIVITY: Alert._Cause.ValueType  # 11
        MEDICAL_EMERGENCY: Alert._Cause.ValueType  # 12

    class Cause(_Cause, metaclass=_CauseEnumTypeWrapper): ...
    UNKNOWN_CAUSE: Alert.Cause.ValueType  # 1
    OTHER_CAUSE: Alert.Cause.ValueType  # 2
    TECHNICAL_PROBLEM: Alert.Cause.ValueType  # 3
    STRIKE: Alert.Cause.ValueType  # 4
    DEMONSTRATION: Alert.Cause.ValueType  # 5
    ACCIDENT: Alert.Cause.ValueType  # 6
    HOLIDAY: Alert.Cause.ValueType  # 7
    WEATHER: Alert.Cause.ValueType  # 8
    MAINTENANCE: Alert.Cause.ValueType  # 9
    CONSTRUCTION: Alert.Cause.ValueType  # 10
    POLICE_ACTIVITY: Alert.Cause.ValueType  # 11
    MEDICAL_EMERGENCY: Alert.Cause.ValueType  # 12

    class _Effect:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EffectEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Alert._Effect.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_SERVICE: Alert._Effect.ValueType  # 1
        REDUCED_SERVICE: Alert._Effect.ValueType  # 2
        SIGNIFICANT_DELAYS: Alert._Effect.ValueType  # 3
        DETOUR: Alert._Effect.ValueType  # 4
        ADDITIONAL_SERVICE: Alert._Effect.ValueType  # 5
        MODIFIED_SERVICE: Alert._Effect.ValueType  # 6
        OTHER_EFFECT: Alert._Effect.ValueType  # 7
        UNKNOWN_EFFECT: Alert._Effect.ValueType  # 8
        STOP_MOVED: Alert._Effect.ValueType  # 9
        NO_EFFECT: Alert._Effect.ValueType  # 10
        ACCESSIBILITY_ISSUE: Alert._Effect.ValueType  # 11

    class Effect(_Effect, metaclass=_EffectEnumTypeWrapper): ...
    NO_SERVICE: Alert.Effect.ValueType  # 1
    REDUCED_SERVICE: Alert.Effect.ValueType  # 2
    SIGNIFICANT_DELAYS: Alert.Effect.ValueType  # 3
    DETOUR: Alert.Effect.ValueType  # 4
    ADDITIONAL_SERVICE: Alert.Effect.ValueType  # 5
    MODIFIED_SERVICE: Alert.Effect.ValueType  # 6
    OTHER_EFFECT: Alert.Effect.ValueType  # 7
    UNKNOWN_EFFECT: Alert.Effect.ValueType  # 8
    STOP_MOVED: Alert.Effect.ValueType  # 9
    NO_EFFECT: Alert.Effect.ValueType  # 10
    ACCESSIBILITY_ISSUE: Alert.Effect.ValueType  # 11

    class _SeverityLevel:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SeverityLevelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Alert._SeverityLevel.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN_SEVERITY: Alert._SeverityLevel.ValueType  # 1
        INFO: Alert._SeverityLevel.ValueType  # 2
        WARNING: Alert._SeverityLevel.ValueType  # 3
        SEVERE: Alert._SeverityLevel.ValueType  # 4

    class SeverityLevel(_SeverityLevel, metaclass=_SeverityLevelEnumTypeWrapper): ...
    UNKNOWN_SEVERITY: Alert.SeverityLevel.ValueType  # 1
    INFO: Alert.SeverityLevel.ValueType  # 2
    WARNING: Alert.SeverityLevel.ValueType  # 3
    SEVERE: Alert.SeverityLevel.ValueType  # 4

    ACTIVE_PERIOD_FIELD_NUMBER: _builtins.int
    INFORMED_ENTITY_FIELD_NUMBER: _builtins.int
    CAUSE_FIELD_NUMBER: _builtins.int
    EFFECT_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    HEADER_TEXT_FIELD_NUMBER: _builtins.int
    DESCRIPTION_TEXT_FIELD_NUMBER: _builtins.int
    TTS_HEADER_TEXT_FIELD_NUMBER: _builtins.int
    TTS_DESCRIPTION_TEXT_FIELD_NUMBER: _builtins.int
    SEVERITY_LEVEL_FIELD_NUMBER: _builtins.int
    cause: Global___Alert.Cause.ValueType
    effect: Global___Alert.Effect.ValueType
    severity_level: Global___Alert.SeverityLevel.ValueType
    @_builtins.property
    def active_period(self) -> _containers.RepeatedCompositeFieldContainer[Global___TimeRange]: ...
    @_builtins.property
    def informed_entity(self) -> _containers.RepeatedCompositeFieldContainer[Global___EntitySelector]: ...
    @_builtins.property
    def url(self) -> Global___TranslatedString: ...
    @_builtins.property
    def header_text(self) -> Global___TranslatedString: ...
    @_builtins.property
    def description_text(self) -> Global___TranslatedString: ...
    @_builtins.property
    def tts_header_text(self) -> Global___TranslatedString: ...
    @_builtins.property
    def tts_description_text(self) -> Global___TranslatedString: ...
    def __init__(
        self,
        *,
        active_period: _abc.Iterable[Global___TimeRange] | None = ...,
        informed_entity: _abc.Iterable[Global___EntitySelector] | None = ...,
        cause: Global___Alert.Cause.ValueType | None = ...,
        effect: Global___Alert.Effect.ValueType | None = ...,
        url: Global___TranslatedString | None = ...,
        header_text: Global___TranslatedString | None = ...,
        description_text: Global___TranslatedString | None = ...,
        tts_header_text: Global___TranslatedString | None = ...,
        tts_description_text: Global___TranslatedString | None = ...,
        severity_level: Global___Alert.SeverityLevel.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cause", b"cause", "description_text", b"description_text", "effect", b"effect", "header_text", b"header_text", "severity_level", b"severity_level", "tts_description_text", b"tts_description_text", "tts_header_text", b"tts_header_text", "url", b"url"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_period", b"active_period", "cause", b"cause", "description_text", b"description_text", "effect", b"effect", "header_text", b"header_text", "informed_entity", b"informed_entity", "severity_level", b"severity_level", "tts_description_text", b"tts_description_text", "tts_header_text", b"tts_header_text", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Alert: _TypeAlias = Alert  # noqa: Y015

@_typing.final
class TimeRange(_message.Message):
    """A time interval."""

    DESCRIPTOR: _descriptor.Descriptor

    START_FIELD_NUMBER: _builtins.int
    END_FIELD_NUMBER: _builtins.int
    start: _builtins.int
    end: _builtins.int
    def __init__(
        self,
        *,
        start: _builtins.int | None = ...,
        end: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["end", b"end", "start", b"start"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end", b"end", "start", b"start"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TimeRange: _TypeAlias = TimeRange  # noqa: Y015

@_typing.final
class Position(_message.Message):
    """A position."""

    DESCRIPTOR: _descriptor.Descriptor

    LATITUDE_FIELD_NUMBER: _builtins.int
    LONGITUDE_FIELD_NUMBER: _builtins.int
    BEARING_FIELD_NUMBER: _builtins.int
    ODOMETER_FIELD_NUMBER: _builtins.int
    SPEED_FIELD_NUMBER: _builtins.int
    latitude: _builtins.float
    longitude: _builtins.float
    bearing: _builtins.float
    odometer: _builtins.float
    speed: _builtins.float
    def __init__(
        self,
        *,
        latitude: _builtins.float | None = ...,
        longitude: _builtins.float | None = ...,
        bearing: _builtins.float | None = ...,
        odometer: _builtins.float | None = ...,
        speed: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bearing", b"bearing", "latitude", b"latitude", "longitude", b"longitude", "odometer", b"odometer", "speed", b"speed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bearing", b"bearing", "latitude", b"latitude", "longitude", b"longitude", "odometer", b"odometer", "speed", b"speed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Position: _TypeAlias = Position  # noqa: Y015

@_typing.final
class TripDescriptor(_message.Message):
    """A descriptor that identifies an instance of a GTFS trip, or all instances of
    a trip along a route.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _ScheduleRelationship:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ScheduleRelationshipEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TripDescriptor._ScheduleRelationship.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SCHEDULED: TripDescriptor._ScheduleRelationship.ValueType  # 0
        ADDED: TripDescriptor._ScheduleRelationship.ValueType  # 1
        UNSCHEDULED: TripDescriptor._ScheduleRelationship.ValueType  # 2
        CANCELED: TripDescriptor._ScheduleRelationship.ValueType  # 3
        @_builtins.property
        @_deprecated("""This enum value has been marked as deprecated using proto enum value options.""")
        def REPLACEMENT(self) -> TripDescriptor._ScheduleRelationship.ValueType: ...  # 5
        DUPLICATED: TripDescriptor._ScheduleRelationship.ValueType  # 6

    class ScheduleRelationship(_ScheduleRelationship, metaclass=_ScheduleRelationshipEnumTypeWrapper): ...
    SCHEDULED: TripDescriptor.ScheduleRelationship.ValueType  # 0
    ADDED: TripDescriptor.ScheduleRelationship.ValueType  # 1
    UNSCHEDULED: TripDescriptor.ScheduleRelationship.ValueType  # 2
    CANCELED: TripDescriptor.ScheduleRelationship.ValueType  # 3
    REPLACEMENT: TripDescriptor.ScheduleRelationship.ValueType  # 5
    DUPLICATED: TripDescriptor.ScheduleRelationship.ValueType  # 6

    TRIP_ID_FIELD_NUMBER: _builtins.int
    ROUTE_ID_FIELD_NUMBER: _builtins.int
    DIRECTION_ID_FIELD_NUMBER: _builtins.int
    START_TIME_FIELD_NUMBER: _builtins.int
    START_DATE_FIELD_NUMBER: _builtins.int
    SCHEDULE_RELATIONSHIP_FIELD_NUMBER: _builtins.int
    trip_id: _builtins.str
    route_id: _builtins.str
    direction_id: _builtins.int
    start_time: _builtins.str
    start_date: _builtins.str
    schedule_relationship: Global___TripDescriptor.ScheduleRelationship.ValueType
    def __init__(
        self,
        *,
        trip_id: _builtins.str | None = ...,
        route_id: _builtins.str | None = ...,
        direction_id: _builtins.int | None = ...,
        start_time: _builtins.str | None = ...,
        start_date: _builtins.str | None = ...,
        schedule_relationship: Global___TripDescriptor.ScheduleRelationship.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["direction_id", b"direction_id", "route_id", b"route_id", "schedule_relationship", b"schedule_relationship", "start_date", b"start_date", "start_time", b"start_time", "trip_id", b"trip_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["direction_id", b"direction_id", "route_id", b"route_id", "schedule_relationship", b"schedule_relationship", "start_date", b"start_date", "start_time", b"start_time", "trip_id", b"trip_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TripDescriptor: _TypeAlias = TripDescriptor  # noqa: Y015

@_typing.final
class VehicleDescriptor(_message.Message):
    """Identification information for the vehicle performing the trip."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    LICENSE_PLATE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    label: _builtins.str
    license_plate: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str | None = ...,
        label: _builtins.str | None = ...,
        license_plate: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "label", b"label", "license_plate", b"license_plate"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "label", b"label", "license_plate", b"license_plate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VehicleDescriptor: _TypeAlias = VehicleDescriptor  # noqa: Y015

@_typing.final
class EntitySelector(_message.Message):
    """A selector for an entity in a GTFS feed."""

    DESCRIPTOR: _descriptor.Descriptor

    AGENCY_ID_FIELD_NUMBER: _builtins.int
    ROUTE_ID_FIELD_NUMBER: _builtins.int
    ROUTE_TYPE_FIELD_NUMBER: _builtins.int
    TRIP_FIELD_NUMBER: _builtins.int
    STOP_ID_FIELD_NUMBER: _builtins.int
    DIRECTION_ID_FIELD_NUMBER: _builtins.int
    agency_id: _builtins.str
    route_id: _builtins.str
    route_type: _builtins.int
    stop_id: _builtins.str
    direction_id: _builtins.int
    @_builtins.property
    def trip(self) -> Global___TripDescriptor: ...
    def __init__(
        self,
        *,
        agency_id: _builtins.str | None = ...,
        route_id: _builtins.str | None = ...,
        route_type: _builtins.int | None = ...,
        trip: Global___TripDescriptor | None = ...,
        stop_id: _builtins.str | None = ...,
        direction_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["agency_id", b"agency_id", "direction_id", b"direction_id", "route_id", b"route_id", "route_type", b"route_type", "stop_id", b"stop_id", "trip", b"trip"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["agency_id", b"agency_id", "direction_id", b"direction_id", "route_id", b"route_id", "route_type", b"route_type", "stop_id", b"stop_id", "trip", b"trip"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EntitySelector: _TypeAlias = EntitySelector  # noqa: Y015

@_typing.final
class TranslatedString(_message.Message):
    """An internationalized message containing per-language versions of a snippet of
    text or a URL.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Translation(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TEXT_FIELD_NUMBER: _builtins.int
        LANGUAGE_FIELD_NUMBER: _builtins.int
        text: _builtins.str
        language: _builtins.str
        def __init__(
            self,
            *,
            text: _builtins.str | None = ...,
            language: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["language", b"language", "text", b"text"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["language", b"language", "text", b"text"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TRANSLATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def translation(self) -> _containers.RepeatedCompositeFieldContainer[Global___TranslatedString.Translation]: ...
    def __init__(
        self,
        *,
        translation: _abc.Iterable[Global___TranslatedString.Translation] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["translation", b"translation"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TranslatedString: _TypeAlias = TranslatedString  # noqa: Y015
