"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
MTA Railroad (LIRR / Metro-North) GTFS-realtime extensions.
Source: https://github.com/OneBusAway/onebusaway-gtfs-realtime-api/blob/master/src/main/proto/com/google/transit/realtime/gtfs-realtime-MTARR.proto
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf.internal import extension_dict as _extension_dict
import builtins as _builtins
from nibble.protos import gtfs_realtime_pb2 as _gtfs_realtime_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MtaRailroadStopTimeUpdate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRACK_FIELD_NUMBER: _builtins.int
    TRAINSTATUS_FIELD_NUMBER: _builtins.int
    track: _builtins.str
    trainStatus: _builtins.str
    def __init__(
        self,
        *,
        track: _builtins.str | None = ...,
        trainStatus: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["track", b"track", "trainStatus", b"trainStatus"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "track", b"track", "trainStatus", b"trainStatus"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MtaRailroadStopTimeUpdate: _TypeAlias = MtaRailroadStopTimeUpdate  # noqa: Y015

@_typing.final
class MtaRailroadCarriageDetails(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _QuietCarriage:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _QuietCarriageEnumTypeWrapper(
        _enum_type_wrapper._EnumTypeWrapper[MtaRailroadCarriageDetails._QuietCarriage.ValueType],
        _builtins.type,
    ):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN_QUIET_CARRIAGE: MtaRailroadCarriageDetails._QuietCarriage.ValueType  # 0
        QUIET_CARRIAGE: MtaRailroadCarriageDetails._QuietCarriage.ValueType  # 1
        NOT_QUIET_CARRIAGE: MtaRailroadCarriageDetails._QuietCarriage.ValueType  # 2

    class QuietCarriage(_QuietCarriage, metaclass=_QuietCarriageEnumTypeWrapper): ...
    UNKNOWN_QUIET_CARRIAGE: MtaRailroadCarriageDetails.QuietCarriage.ValueType  # 0
    QUIET_CARRIAGE: MtaRailroadCarriageDetails.QuietCarriage.ValueType  # 1
    NOT_QUIET_CARRIAGE: MtaRailroadCarriageDetails.QuietCarriage.ValueType  # 2

    class _ToiletFacilities:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ToiletFacilitiesEnumTypeWrapper(
        _enum_type_wrapper._EnumTypeWrapper[MtaRailroadCarriageDetails._ToiletFacilities.ValueType],
        _builtins.type,
    ):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN_TOILET_FACILITIES: MtaRailroadCarriageDetails._ToiletFacilities.ValueType  # 0
        TOILET_ONBOARD: MtaRailroadCarriageDetails._ToiletFacilities.ValueType  # 1
        NO_TOILET_ONBOARD: MtaRailroadCarriageDetails._ToiletFacilities.ValueType  # 2

    class ToiletFacilities(_ToiletFacilities, metaclass=_ToiletFacilitiesEnumTypeWrapper): ...
    UNKNOWN_TOILET_FACILITIES: MtaRailroadCarriageDetails.ToiletFacilities.ValueType  # 0
    TOILET_ONBOARD: MtaRailroadCarriageDetails.ToiletFacilities.ValueType  # 1
    NO_TOILET_ONBOARD: MtaRailroadCarriageDetails.ToiletFacilities.ValueType  # 2

    BICYCLES_ALLOWED_FIELD_NUMBER: _builtins.int
    CARRIAGE_CLASS_FIELD_NUMBER: _builtins.int
    QUIET_CARRIAGE_FIELD_NUMBER: _builtins.int
    TOILET_FACILITIES_FIELD_NUMBER: _builtins.int
    bicycles_allowed: _builtins.int
    carriage_class: _builtins.str
    quiet_carriage: Global___MtaRailroadCarriageDetails.QuietCarriage.ValueType
    toilet_facilities: Global___MtaRailroadCarriageDetails.ToiletFacilities.ValueType
    def __init__(
        self,
        *,
        bicycles_allowed: _builtins.int | None = ...,
        carriage_class: _builtins.str | None = ...,
        quiet_carriage: Global___MtaRailroadCarriageDetails.QuietCarriage.ValueType | None = ...,
        toilet_facilities: Global___MtaRailroadCarriageDetails.ToiletFacilities.ValueType
        | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "bicycles_allowed",
        b"bicycles_allowed",
        "carriage_class",
        b"carriage_class",
        "quiet_carriage",
        b"quiet_carriage",
        "toilet_facilities",
        b"toilet_facilities",
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "bicycles_allowed",
        b"bicycles_allowed",
        "carriage_class",
        b"carriage_class",
        "quiet_carriage",
        b"quiet_carriage",
        "toilet_facilities",
        b"toilet_facilities",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MtaRailroadCarriageDetails: _TypeAlias = MtaRailroadCarriageDetails  # noqa: Y015

MTA_RAILROAD_STOP_TIME_UPDATE_FIELD_NUMBER: _builtins.int
MTA_RAILROAD_CARRIAGE_DETAILS_FIELD_NUMBER: _builtins.int
mta_railroad_stop_time_update: _extension_dict._ExtensionFieldDescriptor[
    _gtfs_realtime_pb2.TripUpdate.StopTimeUpdate, Global___MtaRailroadStopTimeUpdate
]
mta_railroad_carriage_details: _extension_dict._ExtensionFieldDescriptor[
    _gtfs_realtime_pb2.VehiclePosition.CarriageDetails, Global___MtaRailroadCarriageDetails
]
