"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2012 Metropolitan Transportation Authority

Protocol definition for NYCT-specific extensions to GTFS-realtime.

Source: https://groups.google.com/d/msg/gtfs-realtime/KWJhkXH0kBg/8rlRMxiL-ysJ
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf.internal import extension_dict as _extension_dict
import builtins as _builtins
from nibble.protos import gtfs_realtime_pb2 as _gtfs_realtime_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class TripReplacementPeriod(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ROUTE_ID_FIELD_NUMBER: _builtins.int
    REPLACEMENT_PERIOD_FIELD_NUMBER: _builtins.int
    route_id: _builtins.str
    """The replacement period is for this route"""
    @_builtins.property
    def replacement_period(self) -> _gtfs_realtime_pb2.TimeRange:
        """The start time is omitted, the end time is currently now + 30 minutes for
        all routes of the A division
        """

    def __init__(
        self,
        *,
        route_id: _builtins.str | None = ...,
        replacement_period: _gtfs_realtime_pb2.TimeRange | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["replacement_period", b"replacement_period", "route_id", b"route_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["replacement_period", b"replacement_period", "route_id", b"route_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TripReplacementPeriod: _TypeAlias = TripReplacementPeriod  # noqa: Y015

@_typing.final
class NyctFeedHeader(_message.Message):
    """NYCT Subway extensions for the feed header"""

    DESCRIPTOR: _descriptor.Descriptor

    NYCT_SUBWAY_VERSION_FIELD_NUMBER: _builtins.int
    TRIP_REPLACEMENT_PERIOD_FIELD_NUMBER: _builtins.int
    nyct_subway_version: _builtins.str
    """Version of the NYCT Subway extensions
    The current version is 1.0
    """
    @_builtins.property
    def trip_replacement_period(self) -> _containers.RepeatedCompositeFieldContainer[Global___TripReplacementPeriod]:
        """For the NYCT Subway, the GTFS-realtime feed replaces any scheduled
        trip within the trip_replacement_period.
        This feed is a full dataset, it contains all trips starting
        in the trip_replacement_period. If a trip from the static GTFS is not
        found in the GTFS-realtime feed, it should be considered as cancelled.
        """

    def __init__(
        self,
        *,
        nyct_subway_version: _builtins.str | None = ...,
        trip_replacement_period: _abc.Iterable[Global___TripReplacementPeriod] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["nyct_subway_version", b"nyct_subway_version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["nyct_subway_version", b"nyct_subway_version", "trip_replacement_period", b"trip_replacement_period"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NyctFeedHeader: _TypeAlias = NyctFeedHeader  # noqa: Y015

@_typing.final
class NyctTripDescriptor(_message.Message):
    """NYCT Subway extensions for the trip descriptor"""

    DESCRIPTOR: _descriptor.Descriptor

    class _Direction:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _DirectionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[NyctTripDescriptor._Direction.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NORTH: NyctTripDescriptor._Direction.ValueType  # 1
        EAST: NyctTripDescriptor._Direction.ValueType  # 2
        SOUTH: NyctTripDescriptor._Direction.ValueType  # 3
        WEST: NyctTripDescriptor._Direction.ValueType  # 4

    class Direction(_Direction, metaclass=_DirectionEnumTypeWrapper):
        """The direction the train is moving."""

    NORTH: NyctTripDescriptor.Direction.ValueType  # 1
    EAST: NyctTripDescriptor.Direction.ValueType  # 2
    SOUTH: NyctTripDescriptor.Direction.ValueType  # 3
    WEST: NyctTripDescriptor.Direction.ValueType  # 4

    TRAIN_ID_FIELD_NUMBER: _builtins.int
    IS_ASSIGNED_FIELD_NUMBER: _builtins.int
    DIRECTION_FIELD_NUMBER: _builtins.int
    train_id: _builtins.str
    """The nyct_train_id is meant for internal use only. It provides an
    easy way to associate GTFS-realtime trip identifiers with NYCT rail
    operations identifiers.

    The ATS office system assigns unique train identification (Train ID) to
    each train operating within or ready to enter the mainline of the
    monitored territory. An example of this is 06 0123+ PEL/BBR and is decoded
    as follows:

    The first character represents the trip type designator. 0 identifies a
    scheduled revenue trip. Other revenue trip values that are a result of a
    change to the base schedule include; [= reroute], [/ skip stop], [$ turn
    train] also known as shortly lined service.

    The second character 6 represents the trip line i.e. number 6 train. The
    third set of characters identify the decoded origin time. The last
    character may be blank "on the whole minute" or + "30 seconds".

    Note: Origin times will not change when there is a trip type change. This
    is followed by a three character "Origin Location" / "Destination Location"
    """
    is_assigned: _builtins.bool
    """This trip has been assigned to a physical train. If true, this trip is
    already underway or most likely will depart shortly.

    Train Assignment is a function of the Automatic Train Supervision (ATS)
    office system used by NYCT Rail Operations to monitor and track train
    movements. ATS provides the ability to "assign" the nyct_train_id
    attribute when a physical train is at its origin terminal. These assigned
    trips have the is_assigned field set in the TripDescriptor.

    When a train is at a terminal but has not been given a work program it is
    declared unassigned and is tagged as such. Unassigned trains can be moved
    to a storage location or assigned a nyct_train_id when a determination for
    service is made.
    """
    direction: Global___NyctTripDescriptor.Direction.ValueType
    """Uptown and Bronx-bound trains are moving NORTH.
    Times Square Shuttle to Grand Central is also northbound.

    Downtown and Brooklyn-bound trains are moving SOUTH.
    Times Square Shuttle to Times Square is also southbound.

    EAST and WEST are not used currently.
    """
    def __init__(
        self,
        *,
        train_id: _builtins.str | None = ...,
        is_assigned: _builtins.bool | None = ...,
        direction: Global___NyctTripDescriptor.Direction.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["direction", b"direction", "is_assigned", b"is_assigned", "train_id", b"train_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["direction", b"direction", "is_assigned", b"is_assigned", "train_id", b"train_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NyctTripDescriptor: _TypeAlias = NyctTripDescriptor  # noqa: Y015

@_typing.final
class NyctStopTimeUpdate(_message.Message):
    """NYCT Subway extensions for the stop time update"""

    DESCRIPTOR: _descriptor.Descriptor

    SCHEDULED_TRACK_FIELD_NUMBER: _builtins.int
    ACTUAL_TRACK_FIELD_NUMBER: _builtins.int
    scheduled_track: _builtins.str
    """Provides the planned station arrival track. The following is the Manhattan
    track configuration:
    1: southbound local
    2: southbound express
    3: northbound express
    4: northbound local

    In the Bronx (except Dyre Ave line):
    M: bi-directional express (AM express to Manhattan, PM express away).

    The Dyre Ave line is configured:
    1: southbound
    2: northbound
    3: bi-directional
    """
    actual_track: _builtins.str
    """This is the actual track that the train is operating on and can be used to
    determine if a train is operating according to its current schedule (plan).

    The actual track is known only shortly before the train reaches a station,
    typically not before it leaves the previous station. Therefore, the NYCT
    feed sets this field only for the first station of the remaining trip.

    Different actual and scheduled track is the result of manually rerouting a
    train off its scheduled path. When this occurs, prediction data may become
    unreliable since the train is no longer operating in accordance with its
    schedule.
    """
    def __init__(
        self,
        *,
        scheduled_track: _builtins.str | None = ...,
        actual_track: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["actual_track", b"actual_track", "scheduled_track", b"scheduled_track"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actual_track", b"actual_track", "scheduled_track", b"scheduled_track"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NyctStopTimeUpdate: _TypeAlias = NyctStopTimeUpdate  # noqa: Y015

NYCT_FEED_HEADER_FIELD_NUMBER: _builtins.int
NYCT_TRIP_DESCRIPTOR_FIELD_NUMBER: _builtins.int
NYCT_STOP_TIME_UPDATE_FIELD_NUMBER: _builtins.int
nyct_feed_header: _extension_dict._ExtensionFieldDescriptor[_gtfs_realtime_pb2.FeedHeader, Global___NyctFeedHeader]
nyct_trip_descriptor: _extension_dict._ExtensionFieldDescriptor[_gtfs_realtime_pb2.TripDescriptor, Global___NyctTripDescriptor]
nyct_stop_time_update: _extension_dict._ExtensionFieldDescriptor[_gtfs_realtime_pb2.TripUpdate.StopTimeUpdate, Global___NyctStopTimeUpdate]
